[package]
name = "dicom_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2.33"
byteorder = "1.5.0"
memmap2 = "0.9.4"
once_cell = "1.19.0"
