use crate::dataset::value_representation::ValueRepresentation;

pub const APPLICATION_ENTITY : ValueRepresentation = ValueRepresentation { value: *b"AE" };
pub const AGE_STRING : ValueRepresentation = ValueRepresentation { value: *b"AS" };
pub const ATTRIBUTE_TAG : ValueRepresentation = ValueRepresentation { value: *b"AT" };
pub const CODE_STRING : ValueRepresentation = ValueRepresentation { value: *b"CS" };
pub const DATE : ValueRepresentation = ValueRepresentation { value: *b"DA" };
pub const DECIMAL_STRING : ValueRepresentation = ValueRepresentation { value: *b"DS" };
pub const DATE_TIME : ValueRepresentation = ValueRepresentation { value: *b"DT" };
pub const FLOATING_POINT_SINGLE : ValueRepresentation = ValueRepresentation { value: *b"FL" };
pub const FLOATING_POINT_DOUBLE : ValueRepresentation = ValueRepresentation { value: *b"FD" };
pub const INTEGER_STRING : ValueRepresentation = ValueRepresentation { value: *b"IS" };
pub const LONG_STRING : ValueRepresentation = ValueRepresentation { value: *b"LO" };
pub const LONG_TEXT : ValueRepresentation = ValueRepresentation { value: *b"LT" };
pub const OTHER_BYTE : ValueRepresentation = ValueRepresentation { value: *b"OB" };
pub const OTHER_DOUBLE : ValueRepresentation = ValueRepresentation { value: *b"OD" };
pub const OTHER_FLOAT : ValueRepresentation = ValueRepresentation { value: *b"OF" };
pub const OTHER_LONG : ValueRepresentation = ValueRepresentation { value: *b"OL" };
pub const OTHER_64_BIT_VERY_LONG : ValueRepresentation = ValueRepresentation { value: *b"OV" };
pub const OTHER_WORD : ValueRepresentation = ValueRepresentation { value: *b"OW" };
pub const PERSON_NAME : ValueRepresentation = ValueRepresentation { value: *b"PN" };
pub const SHORT_STRING : ValueRepresentation = ValueRepresentation { value: *b"SH" };
pub const SIGNED_LONG : ValueRepresentation = ValueRepresentation { value: *b"SL" };
pub const SEQUENCE_OF_ITEMS : ValueRepresentation = ValueRepresentation { value: *b"SQ" };
pub const SIGNED_SHORT : ValueRepresentation = ValueRepresentation { value: *b"SS" };
pub const SHORT_TEXT : ValueRepresentation = ValueRepresentation { value: *b"ST" };
pub const SIGNED_64_BIT_VERY_LONG : ValueRepresentation = ValueRepresentation { value: *b"SV" };
pub const TIME : ValueRepresentation = ValueRepresentation { value: *b"TM" };
pub const UNLIMITED_CHARACTER : ValueRepresentation = ValueRepresentation { value: *b"UC" };
pub const UNIQUE_IDENTIFIER_UID : ValueRepresentation = ValueRepresentation { value: *b"UI" };
pub const UNSIGNED_LONG : ValueRepresentation = ValueRepresentation { value: *b"UL" };
pub const UNKNOWN : ValueRepresentation = ValueRepresentation { value: *b"UN" };

pub const UNIVERSAL_RESOURCE : ValueRepresentation = ValueRepresentation { value: *b"UR" };
pub const UNSIGNED_SHORT : ValueRepresentation = ValueRepresentation { value: *b"US" };
pub const UNLIMITED_TEXT : ValueRepresentation = ValueRepresentation { value: *b"UT" };
pub const UNSIGNED_64_BIT_VERY_LONG : ValueRepresentation = ValueRepresentation { value: *b"UV" };